//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: test.proto
namespace net_protocol
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"PBString")]
    public partial class PBString : global::ProtoBuf.IExtensible
    {
        public PBString() { }

        private string _str_value;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"str_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string str_value
        {
            get { return _str_value; }
            set { _str_value = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"PBInt")]
    public partial class PBInt : global::ProtoBuf.IExtensible
    {
        public PBInt() { }

        private int _int_value;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"int_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int int_value
        {
            get { return _int_value; }
            set { _int_value = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"PBBool")]
    public partial class PBBool : global::ProtoBuf.IExtensible
    {
        public PBBool() { }

        private bool _bool_value;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"bool_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public bool bool_value
        {
            get { return _bool_value; }
            set { _bool_value = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"PBUInt")]
    public partial class PBUInt : global::ProtoBuf.IExtensible
    {
        public PBUInt() { }

        private uint _uint_value;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"uint_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public uint uint_value
        {
            get { return _uint_value; }
            set { _uint_value = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"PBFloat")]
    public partial class PBFloat : global::ProtoBuf.IExtensible
    {
        public PBFloat() { }

        private float _float_value;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"float_value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public float float_value
        {
            get { return _float_value; }
            set { _float_value = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"PBPoker")]
    public partial class PBPoker : global::ProtoBuf.IExtensible
    {
        public PBPoker() { }

        private string _str_value;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"str_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string str_value
        {
            get { return _str_value; }
            set { _str_value = value; }
        }
        private int _int_value;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"int_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int int_value
        {
            get { return _int_value; }
            set { _int_value = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"PBPokerList")]
    public partial class PBPokerList : global::ProtoBuf.IExtensible
    {
        public PBPokerList() { }

        private readonly global::System.Collections.Generic.List<net_protocol.PBPoker> _value = new global::System.Collections.Generic.List<net_protocol.PBPoker>();
        [global::ProtoBuf.ProtoMember(1, Name = @"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<net_protocol.PBPoker> value
        {
            get { return _value; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"PlayerData")]
    public partial class PlayerData : global::ProtoBuf.IExtensible
    {
        public PlayerData() { }

        private int _roleID;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"roleID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int roleID
        {
            get { return _roleID; }
            set { _roleID = value; }
        }
        private net_protocol.PBPokerList _pokerlist;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"pokerlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public net_protocol.PBPokerList pokerlist
        {
            get { return _pokerlist; }
            set { _pokerlist = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

}