//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: test.proto
namespace net_protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBString")]
  public partial class PBString : global::ProtoBuf.IExtensible
  {
    public PBString() {}
    
    private string _str_value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"str_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string str_value
    {
      get { return _str_value; }
      set { _str_value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}